use super::{CategoryDef, CategoryGroup, Method, Risk};

pub fn get_linux_categories() -> Vec<CategoryDef> {
    vec![
        CategoryDef {
            id: "npm_cache",
            name: "npm cache",
            description: "Cache global paket dan package tarball npm",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.npm/_cacache"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "pnpm_store",
            name: "pnpm store",
            description: "Paket unreferenced di penyimpanan global pnpm",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Safe,
            paths_patterns: &["~/.local/share/pnpm/store"],
            command: Some("pnpm store prune"),
            cli_name: Some("pnpm"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "yarn_cache",
            name: "Yarn cache",
            description: "Cache paket Yarn v1/v2 global",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.cache/yarn"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "bun_cache",
            name: "Bun cache",
            description: "Cache download package Bun",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.bun/install/cache"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "cargo_registry",
            name: "Cargo registry cache",
            description: "Cache crates.io registry dan git index Cargo",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.cargo/registry/cache", "~/.cargo/registry/src"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "cargo_git",
            name: "Cargo git checkouts",
            description: "Cache repository git dependencies Cargo",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.cargo/git/checkouts"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "playwright",
            name: "Playwright browsers",
            description: "Binary headless browser Playwright (Chromium, Firefox, WebKit)",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/.cache/ms-playwright"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "puppeteer",
            name: "Puppeteer browsers",
            description: "Binary browser Chrome Puppeteer yang diunduh",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/.cache/puppeteer"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "homebrew",
            name: "Linuxbrew cache",
            description: "Cache unduhan botol dan source Homebrew / Linuxbrew",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Safe,
            paths_patterns: &["~/.cache/Homebrew"],
            command: Some("brew cleanup --prune=all"),
            cli_name: Some("brew"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "docker",
            name: "Docker (prune)",
            description: "Image, container, dan cache build Docker yang tidak terpakai",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Caution,
            paths_patterns: &[],
            command: Some("docker system prune -f"),
            cli_name: Some("docker"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "vscode_cache",
            name: "VS Code cache",
            description: "Cache data, VSIX extension, dan storage VS Code",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &[
                "~/.config/Code/Cache",
                "~/.config/Code/CachedData",
                "~/.config/Code/CachedExtensionVSIXs",
            ],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "user_caches",
            name: "Cache aplikasi pengguna",
            description: "Cache aplikasi pengguna di ~/.cache (per aplikasi)",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/.cache"],
            command: None,
            cli_name: None,
            split_subfolders: true,
        },
    ]
}
