use super::{CategoryDef, CategoryGroup, Method, Risk};

pub fn get_macos_categories() -> Vec<CategoryDef> {
    vec![
        CategoryDef {
            id: "npm_cache",
            name: "npm cache",
            description: "Cache global paket dan package tarball npm",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.npm/_cacache"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "pnpm_store",
            name: "pnpm store",
            description: "Paket unreferenced di penyimpanan global pnpm",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Safe,
            paths_patterns: &["~/Library/pnpm/store"],
            command: Some("pnpm store prune"),
            cli_name: Some("pnpm"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "yarn_cache",
            name: "Yarn cache",
            description: "Cache paket Yarn v1/v2 global",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/Library/Caches/Yarn"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "bun_cache",
            name: "Bun cache",
            description: "Cache download package Bun",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.bun/install/cache"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "cargo_registry",
            name: "Cargo registry cache",
            description: "Cache crates.io registry dan git index Cargo",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.cargo/registry/cache", "~/.cargo/registry/src"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "cargo_git",
            name: "Cargo git checkouts",
            description: "Cache repository git dependencies Cargo",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/.cargo/git/checkouts"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "playwright",
            name: "Playwright browsers",
            description: "Binary headless browser Playwright (Chromium, Firefox, WebKit)",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/Library/Caches/ms-playwright"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "puppeteer",
            name: "Puppeteer browsers",
            description: "Binary browser Chrome Puppeteer yang diunduh",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/.cache/puppeteer"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "xcode_derived",
            name: "Xcode DerivedData",
            description: "Build cache dan indeks perantara proyek Xcode",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &["~/Library/Developer/Xcode/DerivedData"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "ios_sim",
            name: "Simulator tidak terpakai",
            description: "Cache runtime iOS simulator yang tidak dapat diakses",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Safe,
            paths_patterns: &[],
            command: Some("xcrun simctl delete unavailable"),
            cli_name: Some("xcrun"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "xcode_archives",
            name: "Xcode Archives",
            description: "Arsip build & bundle aplikasi lama Xcode",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/Library/Developer/Xcode/Archives"],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "homebrew",
            name: "Homebrew cache",
            description: "Cache unduhan botol dan source Homebrew",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Safe,
            paths_patterns: &["~/Library/Caches/Homebrew"],
            command: Some("brew cleanup --prune=all"),
            cli_name: Some("brew"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "docker",
            name: "Docker (prune)",
            description: "Image, container, dan cache build Docker yang tidak terpakai",
            group: CategoryGroup::Global,
            method: Method::Command,
            risk: Risk::Caution,
            paths_patterns: &[],
            command: Some("docker system prune -f"),
            cli_name: Some("docker"),
            split_subfolders: false,
        },
        CategoryDef {
            id: "vscode_cache",
            name: "VS Code cache",
            description: "Cache data, VSIX extension, dan storage VS Code",
            group: CategoryGroup::Global,
            method: Method::Delete,
            risk: Risk::Safe,
            paths_patterns: &[
                "~/Library/Application Support/Code/Cache",
                "~/Library/Application Support/Code/CachedData",
                "~/Library/Application Support/Code/CachedExtensionVSIXs",
            ],
            command: None,
            cli_name: None,
            split_subfolders: false,
        },
        CategoryDef {
            id: "user_caches",
            name: "Cache aplikasi umum",
            description: "Cache aplikasi pengguna di Library/Caches (per aplikasi)",
            group: CategoryGroup::Global,
            method: Method::Trash,
            risk: Risk::Caution,
            paths_patterns: &["~/Library/Caches"],
            command: None,
            cli_name: None,
            split_subfolders: true,
        },
    ]
}
